config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'my_services', to: 'pages#my_services'
  get 'my_bookings', to: 'pages#my_bookings'

  resources :services do
    resources :bookings, only:[:new, :create]
  end
  resources :bookings do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/service.rb
class Service < ApplicationRecord
  include PgSearch
  # multisearchable against: [:category, :description]
  pg_search_scope :search_by_category_and_description,
  against: [:category, :description],
  using: {
    tsearch: { prefix: true }
  }
  belongs_to :user
  has_many :bookings, dependent: :destroy
  CATEGORIES = ["Government Departments", "Forms", "Trips", "Health and Diet", "Neighborhoods"]
  validates_inclusion_of :category, in: CATEGORIES
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :services
  has_many :bookings
  has_many :reviews, through: :bookings
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_service, only: [:new, :create]

  def index
  end

  def new
    @picture = {
  "Neighborhood" => "https://res.cloudinary.com/dzgpovo2n/image/upload/v1550666525/Neighborhoods.jpg",
  "Trips" => "https://res.cloudinary.com/dzgpovo2n/image/upload/v1550666525/Trips.jpg",
  "Government Departments" => "https://res.cloudinary.com/dzgpovo2n/image/upload/v1550666525/Government%20Departments.jpg",
  "Health and Diet" => "https://res.cloudinary.com/dzgpovo2n/image/upload/v1550666524/Health%20and%20Diet.jpg",
  "Forms" => "https://res.cloudinary.com/dzgpovo2n/image/upload/v1550666524/Forms.jpg"
  }
    @booking = Booking.new
  end

  def update
    @booking.update(booking_params)
    redirect_to my_services_path
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.service = @service
    @booking.user = current_user
    @booking.save!
    redirect_to my_bookings_path

    # Also set price of the booking!
  end

  def destroy
    @booking.destroy
    redirect_back fallback_location: my_bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_service
    @service = Service.find(params[:service_id])
  end

  def booking_params
    params.require(:booking).permit(:description, :time, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @service = Service.new
  end

  def my_services
    # maybe delete this part - who is using this?
    @user = current_user
    @services = @user.services
    # delete the above

    @my_services = Service.where(user_id: current_user.id)
    ## FIX THIS ABOVE
  end

  def my_bookings
    @my_bookings = current_user.bookings
  end

  def my_profile
    @my_profile = current_user
  end

  private

  def set_params
    params.require(:results).permit(:category)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :destroy]
  def index
    #first get all the results with a category
    #then filter for the ones where(location: 'location')
    if params[:category].present?
      @services = Service.search_by_category_and_description("#{params[:category]}")
    elsif params[:description].present?
      @services = Service.search_by_category_and_description("#{params[:description]}")
    else
      @services = Service.all
    end
  end

  def show
  end

  def new
    @service = Service.new
    @service.user = current_user
  end

  def create
    @service = Service.new(services_params)
    @service.user = current_user
    if @service.save
      redirect_to service_path(@service)
    else
      render :new
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path
  end

  def update
    @service = set_service
    @service.update(services_params)
    redirect_to service_path
  end

  def edit
    set_service
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def services_params
    params.require(:service).permit(:name, :description, :category, :price, :query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_helper.rb
module ServiceHelper

end

app/views/bookings/index.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300i" rel="stylesheet">
</head>
<body>
  <br>
  <h2>Which Service Do you Require?</h2>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <input type="text" class="form-control" placeholder="City">
      </div>
      <div class="col-sm">
        <input type="text" class="form-control" placeholder="Category">
      </div>
      <div class="col-sm">
        <input type="text" class="form-control" placeholder="Time">
      </div>
      <div class="col-sm">
        <input type="text" class="form-control" placeholder="Price Range">
      </div>
    </div>
  </div>
  <br>
  <br>

  <!-- cards -->
  <div class="container">
    <div class="row">
      <% @services.each do |service| %>
      <div class="col-xs-12 col-sm-6 col-md-4" style="padding: 10px">
        <%= link_to service_path(service) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/random')">
          <div class="card-content">
            <%= service.description %>
            <h3><%= service.name %></h3>
          </div>
          <img class="avatar" src='https://kitt.lewagon.com/placeholder/users/cveneziani'/>
        </div>
      <% end %>
      </div>
      <%end %>
    </div>
  </div>
</body>

app/views/bookings/new.html.erb
<div class="wrapper-bookings">
  <div class="flex-container">

    <!-- CARD -->

            <div class="card-category-bookings" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @picture[@service.category] %>)">
              <div class="card-name-bookings">
                <h3><%= @service.category %></h3>
              </div>
              <div class="card-content-bookings">
                 <p> <%= @service.description %></p>
                <img class="avatar-card" src='https://kitt.lewagon.com/placeholder/users/cveneziani'/>
              </div>
            </div>



  <!-- INFO -->

    <div class="flex-body">
      <h2 class="booking-page">Description:</h2>
      <p class="make-booking"> <%= @service.description %></p>
      <h2 class="booking-page">Category:</h2>
      <p class="make-booking"> <%= @service.category %></p>
      <h2 class="booking-page">Mench Name:</h2>
      <p class="make-booking"> <%= @service.user.name %></p>
    </div>

  </div>

  <div class="flex-body">

  <!-- TIME -->

    <%= simple_form_for [@service, @booking] do |b| %>
    <%= b.input :time, label: "What time do you need the service?", label_html: { class: "booking-page" }, as: :date_time_picker, input_html:
    { data:{
    date_format: "YYYY.MM.DD hh:mm A",
    date_day_view_header_format: 'MMM YYYY',
    date_side_by_side: true,
    date_min_date: Time.current.strftime('%Y-%m-%d')
    }}%>

  </div>

  <div class="flex-body">

  <!-- MESSAGE -->

    <%= b.input :description, label: "Send a Message to your Mench", input_html: { 'rows' => 5, 'cols' => 1 }, label_html: { class: "booking-page" }, class: "form_control" %>
    <%= b.submit "Create Booking", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Merriweather:700" rel="stylesheet">
<div class="wrapper-bookings">
  <div class="container">
    <div class="row">
      <div class="booking-banner">
        <div class="booking-banner-title">
          <div class="booking-banner-content">
            <h3>Your Bookings</h3>
          </div>
        </div>
        <div class="booking-banner-image">
          <img class="booking-banner-image" src=" <%= cl_image_path @booking.service.category %> ">
        </div>
      </div>
      <div class="description-booking">
        <h3 class="booking">Booking:  </h3>
          <%= @booking.description%>

      </div>
      <div class="button-booking">
        <div class="all-button">
          <%= link_to "Return to Menu", booking_path, class:"btn btn-light"%>
          <%= link_to "Make Booking", new_service_booking_path(@booking.service), class:"btn btn-light"%>
          <% if current_user == @booking.user %>
          <%= link_to "Delete this booking", booking_path(@booking), method: :delete , class: "btn btn-light"  %>
          <%= link_to "Edit", edit_booking_path(@booking), class: "btn btn-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MenchMatch</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="wrapper-home" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.8) 0%, rgba(0,36,61,0.4) 25%), url('<%= image_path 'newbackground.jpg' %>');">
    <div class="center">
      <h3>Find a Mench to help you become a local.</h3>
    </div>
    <div class="form-small">
      <div class="center">
        <%= form_tag services_path, method: :get do %>
        <%= text_field_tag :category, params[:query], class: "form-control", placeholder: "Choose a category" %>
        <br>
        <%= text_field_tag :description, params[:query], class: "form-control", placeholder: "Choose a description" %>
      </div>
    </div>
      <div class="center">
      <%=  submit_tag "Search", class: "btn btn-primary"%>
      <%= link_to "Show Me Everything", services_path, class: "btn btn-success" %>
      <% end %>
      </div>
    <div class="center">
      <p>Getting help for small but meaningful things has never been this easy.</p>
    </div>
</div>

<div></div>

app/views/pages/my_bookings.html.erb
<% if @my_bookings.empty? %>
<h2>Your Bookings Summary</h2>
<h5> You don't have any bookings!</h5><br>
<h5><%= image_tag("mench.jpeg", size: "400") %> </h5>
<% else %>

  <% @my_bookings.each do |booking| %>
    <div class="card-product">
      <img src=<%= cl_image_path booking.service.category %>>
      <div class="card-product-infos">
        <%= link_to booking_path(booking) do %>
          <h2 class="align-left"><%=booking.service.name%></h2>
        <% end %>
        <p><%= booking.description %></p>
        <p>Your Mench is: <strong><%= booking.service.user.name %>!</strong></p>
      </div>
      <div>
        <%= link_to "Cancel", booking_path(booking), method: :delete , class: "btn btn-delete"  %>
        <br><br>
        <p class="approved"><%= booking.status %></p>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/pages/my_services.html.erb
<div class="dashboard-container">
  <h4>The Services you Currently Offer</h4>

  <!-- MY SERVICES CARD -->

  <% @my_services.each do |service| %>
    <div class="card-product">
      <img src= <%= cl_image_path service.category %>>
      <div class="card-product-infos">
        <%= link_to service_path(service) do %>
          <h2 class="align-left"><%=service.name%></h2>
        <% end %>
        <p><%= service.description %></p>
      </div>
      <div>
        <a class="btn btn-delete" href="#">Delete</a>
      </div>
    </div>
  <% end %>

</div>

<div class="dashboard-container">
  <h4>Pending Booking Requests for your Services</h4>

  <!-- MY BOOKINGS  -->

    <% @services.each do |service| %>
    <% service.bookings.each do |booking| %>
      <div class="card-product">
        <img src= <%= cl_image_path booking.service.category %>>

        <div class="card-product-infos">

          <!-- CHANGE THIS LINK ONCE BOOKING SHOW IS READY -->

          <%= link_to service_path(service) do %>

          <!-- CHANGE THIS LINK ONCE BOOKING SHOW IS READY -->
          <div>
            <h2 class="align-left"><%=booking.service.name%></h2>
            <% end %>
            <p><%= booking.service.description %></p>
          </div>
        </div>

          <div class="bookings-center">
            <p id="status"><%= booking.status %></p>

          <%= form_for booking,  method: :patch do |f| %>
          <%= f.hidden_field :status, :value => "Accepted" %>
          <%= f.submit "Approve", class: "btn btn-approve" %>
          <% end %>

          <%= form_for booking,  method: :patch do |f| %>
          <%= f.hidden_field :status, :value => "Declined" %>
          <%= f.submit "Decline", class: "btn btn-decline" %>
          <% end %>

            </div>
        </div>
    <% end %>
    <% end %>

</div>
</div>

app/views/pages/test.html.erb
<h2>The Services you Offer</h2>
<div class="container">
  <div class="row">
    <% @my_services.each do |service| %>
    <div class="col-xs-6 col-sm-6" style="padding: 10px">
      <%= link_to service_path(service) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/random')">
        <div class="card-content">
          <%= service.description %>
          <h3><%= service.category %></h3>
        </div>
        <img class="avatar" src='https://kitt.lewagon.com/placeholder/users/cveneziani'/>
      </div>
      <% end %>
    </div>
    <%end %>
  </div>
</div>
<h2>Pending Booking Requests for your Services</h2>
<div class="container">
  <div class="row">
    <% @services.each do |service| %>
    <% service.bookings.each do |booking| %>
    <div class="col-xs-6 col-sm-6" style="padding: 10px">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/random')">
        <div class="card-content">
          <%= booking.description %>
          <h3><%= booking.service.description %></h3>
        </div>
        <img class="avatar" src='https://kitt.lewagon.com/placeholder/users/cveneziani'/>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/services/edit.html.erb
<div class="row">
  <div class="form-new-service">
    <div class="col-xs-12 col-sm-6">
      <%= simple_form_for(@service) do |f| %>
      <%=f.error_notification  %>

      <div class="form-group">
        <%= f.label "New Service Name" %>
        <%= f.input :name, label: false%>
      </div>


      <div class="form-group">
        <%= f.label "New Service Description" %>
        <%= f.input :description, label: false%>
      </div>
      <div class="form-group">
        <%= f.label "Set New Price" %>
        <%= f.input :price, label: false%>
      </div>
      <%= f.select :category, ["Government Departments", "Forms", "Trips", "Health and Diet", "Neighborhoods"] %>
      <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
</div>

app/views/services/index.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300i" rel="stylesheet">
</head>
<body>
  <br>
  <h2>Which Service Do you Require?</h2>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-8 search-bar">
        <div class="category-search">
          <%= form_tag services_path, method: :get do %>
          <%= text_field_tag :category,
          params[:query],
          class: "form-control",
          placeholder: "Choose a category"
          %>
        </div>

          <br>
          <br>

          <div class="description-search">
            <%= text_field_tag :description,
            params[:query],
            class: "form-control",
            placeholder: "Choose a description"
            %>
          </div>

        <%=  submit_tag "Search", class: "btn btn-primary"%>
        <% end %>
      </div>
      <br>
      <br>
      <!-- cards -->
      <div class="container">
        <div class="row">
          <% @services.each do |service| %>
          <div class="col-xs-12 col-sm-6 col-md-4" style="padding: 10px">
            <%= link_to service_path(service) do %>
            <div class="card-category-service" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path service.category %>')">
              <div class="card-name">
                <h3><%= service.name %></h3>

              </div>
              <div class="card-content">
                 <p> <%= service.description %></p>
                <img class="avatar-card" src='https://kitt.lewagon.com/placeholder/users/cveneziani'/>
              </div>
            </div>
            <% end %>
          </div>
          <%end %>
        </div>
      </div>
    </body>

app/views/services/new.html.erb
<div class="row">
  <div class="form-new-service">
    <div class="col-xs-12 col-sm-6">
      <%= simple_form_for(@service) do |f| %>
      <%=f.error_notification  %>

      <div class="form-group booking-page">
        <%= f.label "Name" %>
        <%= f.input :name, label: false%>
      </div>


      <div class="form-group booking-page">
        <%= f.label "Description" %>
        <%= f.input :description, label: false%>
      </div>
      <div class="form-group booking-page">
        <%= f.label "Price" %>
        <%= f.input :price, label: false%>
      </div>
      <div class="validate-service">
        <%= f.select :category, ["Government Departments", "Forms", "Trips", "Health and Diet", "Neighborhoods"] %>
        <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
  </div>

</div>

app/views/services/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Merriweather:700" rel="stylesheet">
<div class="container">
  <div class="row">
    <div class="service-banner-global">
      <div class="service-banner-title">
        <div class="service-banner-content">
          <h2>Name : </h2>
          <p><%= @service.name.capitalize %></p>
        </div>
      </div>
      <div class="service-banner-image">
        <img class="service-banner-image" src=" <%= cl_image_path @service.category %> ">
      </div>
    </div>
    <div class="description-service">
      <h3>Category :  </h3>
      <p> <%= @service.category %></p>
      <h3>Description : </h3>
      <p><%= @service.description.capitalize %></p>
      <h3>Price : </h3>
      <p> <%= @service.price %> $</p>
    </div>
    <div>
      <div class="all-button-services">
        <div class="button-service-modify">
          <%= link_to "Return to Menu", services_path, class:"btn btn-light"%>
        </div>
        <div class="button-service-modify">
          <%= link_to "Make Booking", new_service_booking_path(@service), class:"btn btn-light"%>
        </div>
        <% if current_user == @service.user %>
        <div class="button-service-modify">
          <%= link_to "Delete this Service", service_path(@service), method: :delete , class: "btn btn-light btn-delete"   %>
          <%= link_to "Edit", edit_service_path(@service), class: "btn btn-light" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= cl_image_tag"mench_match", height: 5, width: 5 %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <!-- Links when logged in -->
    <%= link_to "Host a Service", new_service_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Book a Service", services_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= cl_image_tag current_user.photo , class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to my_services_path do %>
            <i class="fa fa-user"></i> <%= t(".my_services", default: "My Services") %>
            <% end %>
          </li>
          <li>
            <%= link_to my_bookings_path do %>
            <i class="fa fa-cog"></i>  <%= t(".my_bookings", default: "My Bookings") %>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
            <i class="far fa-user"></i>  <%= t(".my_profiles", default: "My Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to my_services_path do %>
          <i class="fa fa-user"></i> <%= t(".my_services", default: "My Services") %>
          <% end %>
        </li>
        <li>
          <%= link_to my_bookings_path do %>
          <i class="fa fa-cog"></i>  <%= t(".my_bookings", default: "My Bookings") %>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
          <i class="far fa-user"></i>  <%= t(".my_profiles", default: "My Profile") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
 <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
          <%= simple_form_for(@service) do |f| %>
            <%=f.error_notification  %>
              <div class=“form-group”>
                <%= f.label "By City" %>
                <%= f.input :city, label: false%>
              </div>
              <div class=“form-group”>
                <%= f.label "By Price" %>
                <%= f.input :price, label: false%>
              </div>
              <div class=“form-group”>
                <%= f.label "By Time" %>
                <%= f.input :time, label: false%>
              </div>
            <%= f.select :category, ["Government Departments", "Forms", "Trips", "Health and Diet", "Neighborhoods"] %>
            <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>